
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
Prisma.prismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.ActorScalarFieldEnum = {
  actor_id: 'actor_id',
  first_name: 'first_name',
  last_name: 'last_name',
  country: 'country',
  birth_date: 'birth_date'
};

exports.Prisma.CustomerScalarFieldEnum = {
  customer_id: 'customer_id',
  first_name: 'first_name',
  last_name: 'last_name',
  email: 'email',
  password: 'password',
  registration_date: 'registration_date',
  is_deleted: 'is_deleted',
  phone: 'phone'
};

exports.Prisma.DirectorScalarFieldEnum = {
  director_id: 'director_id',
  first_name: 'first_name',
  last_name: 'last_name',
  country: 'country'
};

exports.Prisma.FilmScalarFieldEnum = {
  film_id: 'film_id',
  title: 'title',
  release_year: 'release_year',
  duration: 'duration',
  age_restriction: 'age_restriction',
  studio_id: 'studio_id',
  isAvailable: 'isAvailable'
};

exports.Prisma.Film_actorScalarFieldEnum = {
  film_id: 'film_id',
  actor_id: 'actor_id'
};

exports.Prisma.Film_directorScalarFieldEnum = {
  film_id: 'film_id',
  director_id: 'director_id'
};

exports.Prisma.Film_genreScalarFieldEnum = {
  film_id: 'film_id',
  genre_id: 'genre_id'
};

exports.Prisma.GenreScalarFieldEnum = {
  genre_id: 'genre_id',
  name: 'name',
  description: 'description'
};

exports.Prisma.PaymentScalarFieldEnum = {
  payment_id: 'payment_id',
  amount: 'amount',
  payment_type: 'payment_type',
  payment_date: 'payment_date',
  status: 'status',
  customer_id: 'customer_id',
  subscription_id: 'subscription_id'
};

exports.Prisma.StudioScalarFieldEnum = {
  studio_id: 'studio_id',
  name: 'name',
  country: 'country',
  founded_date: 'founded_date'
};

exports.Prisma.SubscriptionScalarFieldEnum = {
  subscription_id: 'subscription_id',
  start_date: 'start_date',
  end_date: 'end_date',
  type: 'type',
  price: 'price',
  customer_id: 'customer_id'
};

exports.Prisma.ReviewScalarFieldEnum = {
  review_id: 'review_id',
  rating: 'rating',
  comment: 'comment',
  created_at: 'created_at',
  film_id: 'film_id',
  customer_id: 'customer_id'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.restriction = exports.$Enums.restriction = {
  R_0: 'R_0',
  R_12: 'R_12',
  R_16: 'R_16',
  R_18: 'R_18',
  R_21: 'R_21'
};

exports.payment_type = exports.$Enums.payment_type = {
  cash: 'cash',
  transfer: 'transfer',
  details: 'details',
  promo: 'promo'
};

exports.subscription_type = exports.$Enums.subscription_type = {
  family: 'family',
  student: 'student',
  standart: 'standart'
};

exports.Prisma.ModelName = {
  actor: 'actor',
  customer: 'customer',
  director: 'director',
  film: 'film',
  film_actor: 'film_actor',
  film_director: 'film_director',
  film_genre: 'film_genre',
  genre: 'genre',
  payment: 'payment',
  studio: 'studio',
  subscription: 'subscription',
  review: 'review'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
